apiVersion: v1
kind: ConfigMap
metadata:
  namespace: node2
  name: full-node-config
data:
  config.toml: |
    [Core]
      IP = ""
      RPCPort = ""
      GRPCPort = ""
    [Key]
      KeyringAccName = ""
    [P2P]
      ListenAddresses = ["/ip4/0.0.0.0/udp/2121/quic", "/ip6/::/udp/2121/quic", "/ip4/0.0.0.0/tcp/2121", "/ip6/::/tcp/2121"]
      AnnounceAddresses = []
      NoAnnounceAddresses = ["/ip4/0.0.0.0/udp/2121/quic", "/ip4/127.0.0.1/tcp/2121/quic", "/ip6/::/udp/2121/quic", "/ip4/0.0.0.0/tcp/2121", "/ip4/127.0.0.1/tcp/2121", "/ip6/::/tcp/2121"]
      Bootstrapper = true
      MutualPeers = ["/dns4/limani.celestia-devops.dev/tcp/2121/p2p/12D3KooWNpRWxpi1APzV6CnwHvdgNRuTUbMNvg4ta2i1fnqYXR7H", "/dns4/parainem.celestia-devops.dev/tcp/2121/p2p/12D3KooWHX8xpwg8qkP7kLKmKGtgZvmsopvgxc6Fwtu665QC7G8q"]
      PeerExchange = true
      RoutingTableRefreshPeriod = 60000000000
    [P2P.ConnManager]
      Low = 50
      High = 100
      GracePeriod = 60000000000
    [RPC]
      Address = "0.0.0.0"
      Port = "26658"
    [Services]
      TrustedHash = ""
      TrustedPeers = []
      PeersLimit = 30
      DiscoveryInterval = 30000000000
      AdvertiseInterval = 30000000000

  OAZHALLLMV4Q: '{"body":"CAESQK6VtdW/knPspBtS1eGLHr7UkxiY40EQSV41rc6JHeYO4GF9BQkz2E+3KPNUsSQwWC2OJwyO4ziyUgwi4TR3Hso="}'
  my_celes_key.info: eyJhbGciOiJQQkVTMi1IUzI1NitBMTI4S1ciLCJjcmVhdGVkIjoiMjAyMi0wOS0wNyAxMTo0MjozOS43OTU3MDA4MjggKzAwMDAgVVRDIG09KzAuMTMxMzEzODQ1IiwiZW5jIjoiQTI1NkdDTSIsInAyYyI6ODE5MiwicDJzIjoiYTNuMjJRb0QwTTl0TGlrWCJ9.QSpWF3KHTSbHTGqY-v7QUtP6TdIIlCcgMD13Z8Wb4Ot2DRKtxUDMfA.UUzWh1z-QoZ5jpNe.1GlkoSocvKUoDzwIUt4L2__wryR4pt9PqHXRY65QDiBRk8JW4xBoWD18eumop6mbQ9c603CmYxbFY9z97TpIJiYMSbLR9uTB-56Kiu5l3P7lmrOik3puA9HaT69U1VE8Ck7i8fMPZqVV7brrjzuV8RENgo9OYZ7VIVoKPFSoTosYvkYRMFJzNLz5LsQrZqjvHt9UhmAh4AqKEtpTfeY7_O58TiSvP3Wy4xXf866LdiAsPM3gWxn9De34OPZKJQOINyH2fJ-M4sX8GDuPdQrVhSHVvIkMVD6vAieXgP1tZ-_EcNcoCcjkSpM9TWWbePmcFc2XAZbnvKD4zqjpCPc4w2ap4lZlgYtfCWe4DbAWsQj3s1SvBf_MClCnQaq1Lwu5r2KzdVn8iyXFEtZn24MVBTk6Xz0kFE5kfrilg7f5IyO2_EjWVtldzJJ5ICtob-4VTPh_bfPUnE0OoY3XZe8v.IevhmntpSJ6Uf6UxIt8bb
  5a846039873bde135ea708fd6355e832a09a12e9.address: eyJhbGciOiJQQkVTMi1IUzI1NitBMTI4S1ciLCJjcmVhdGVkIjoiMjAyMi0wOS0wNyAxMTo0MjozOS44MDkwNDEyMjIgKzAwMDAgVVRDIG09KzAuMTQ0NjU0MjczIiwiZW5jIjoiQTI1NkdDTSIsInAyYyI6ODE5MiwicDJzIjoiQWYwampOX3I5YmV1cGRLaCJ9.VDW7o1-dADhkYEZ87t74Mz6Nv7gS1KSoYE7vnou55iwrVV4aLJ127w.fzuRXvO_mP8aD-Fu.nE6tF_OG_O3SSUdNNHLi8UO1cmrngV8zFBDs6zcq9auzk53gd-RX4ChE7iO_vndsohB-0hqUyaWCvM5yck9ipkHmybt8YkPQyV-TBYQ1AbVQsD-epKXT4ICXqHfdaGvFGpKdN8V8Wpxyj1nunJYG9y5OLNEWmBDFtqAQIgrl-OPfcIqgqwmBJbWz6faisOCruMzyLgb7pbbSxt_p9EBjSCbFpCDmkI1bdk2h273dzYL5fGViM1kZ2mm3oxyHOQ.SLXm4rYGDYdYqF3_IGiPmw
