apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: full-node-data-claim
  namespace: node2
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
